metrics:
  vcpus:
    unit: vcpu
    mutate: NONE
    groupby:
      - id
    metadata:
      - flavor_id
    extra_args:
      aggregation_method: mean
      resource_type: instance
      # See: https://storyboard.openstack.org/#!/story/2008598#comment-170473
      force_granularity: 300
