init_config:
    # These are Nova credentials, [keystone_authtoken] in /etc/nova/nova.conf
    password: <FILL-ME!!!>
    project_name: service
    username: nova
    auth_url: 'http://10.10.10.254:35357'
    region_name: 'RegionOne'
    endpoint_type: 'internalURL'
    project_domain_id: default
    user_domain_id: default
    cache_dir: /dev/shm
    vm_cpu_check_enable: True
    vm_disks_check_enable: False
    vm_network_check_enable: False
    libvirt_type: qemu
    libvirt_uri: qemu+tcp://10.10.10.254/system
instances:
    - {}
